config/routes.rb
Omrails::Application.routes.draw do
  get 'about' => 'pages#about'
  root :to => 'pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>Copyright 2013 Fee Pigeon</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
 
      <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
 
      <!-- Be sure to leave the brand out there if you want it shown -->
      <a class="brand" href="#">Fee Pigeon</a>
 
      <!-- Everything you want hidden at 940px or less, place within here -->
      <div class="nav-collapse collapse">
		<ul class="nav">
			<li><%= link_to "Home", root_path %></li>
			<li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav pull-right">
			<li><%= link_to "Sign Up", '#' %></li>
			<li><%= link_to "Login", '#' %></li>
      </ul>
      </div>
 
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fee Pigeon</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<%= render 'layouts/header' %>
		<%= yield %>
		<%= render 'layouts/footer' %>
	</div>
</body>
</html>

app/views/pages/about.html.erb
<h1>Fee Pigeon: About</h1>
<p>
	Founded by staffing firm executives, Fee Pigeon was designed to bring transparency, honesty, and profit to contingency recruiting practices. 
</p>

app/views/pages/home.html.erb
<h1>Fee Pigeon: Home</h1>
<p>
	Start getting paid for placements you've made that you never knew about.<br/>
	<a href="http://www.feepigeon.com/about">Get started now!</a>
</p>